### PR TITLE
telepresence: Hardcode docker image version

### PR DESCRIPTION
**Pull request by fxleblanc**
review @aviau

### CODE REVIEW

**Comment by aviau** [comment]
Did you try it? it works?

**Comment by aviau** [comment]
Can we refer to that string from setup.py?

**Comment by aviau** [comment]
other than that lgtm feel free to ship it whenever

**Comment by aviau** [comment]
Then you have to open a corresponding PR in pyro. and tag this repository `flared/0.104-2` or something

**Comment by fxleblanc** [comment]
It works. I made the changes directly in my python package in my venv to test. I then pasted the change in the PR.

**Pull request merged**
